# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfigurationRelease: 'Release'
  buildConfigurationStaging: 'Stg'

steps:
- script: dir $(Build.SourcesDirectory)\mtgcustomdecksbuilder.client
  displayName: 'List DIR Contents client'
- script: dir $(Build.SourcesDirectory)\mtgcustomdecksbuilder.server
  displayName: 'List DIR Contents server'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: 'MtgCustomDecksBuilder.Server/MtgCustomDecksBuilder.Server.csproj'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.Staging.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfigurationStaging)'
  displayName: 'Build Staging Server'

- task: VSBuild@1
  inputs:
    solution: 'MtgCustomDecksBuilder.Server/MtgCustomDecksBuilder.Server.csproj'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.Production.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfigurationRelease)'
  displayName: 'Build Production Server'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  displayName: 'Install Angular Dependencies'
  inputs:
    workingDirectory: 'mtgcustomdecksbuilder.client'
    script: 'npm install'

- script: |
    npm run build mtgcustomdecksbuilder.client --configuration=staging
  workingDirectory: 'mtgcustomdecksbuilder.client'
  displayName: 'Build Angular Client (Staging)'

- task: CopyFiles@2
  displayName: 'Prepare Docker Context for Angular Client (Staging)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/mtgcustomdecksbuilder.client'
    Contents: |
      Dockerfile
      dist/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)/docker-client-staging'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/docker-client-staging'
    artifactName: 'docker-client-staging'
    publishLocation: 'Container'

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathToPublish: 'mtgcustomdecksbuilder.client/dist/mtgcustomdecksbuilder.client'
#     artifactName: 'client-staging'
#     publishLocation: 'Container'
#   displayName: 'Publish Angular Client (Staging)'

# - task: Docker@2
#   displayName: 'Build Angular Client Docker Image (Staging)'
#   inputs:
#     command: 'build'
#     dockerfile: 'mtgcustomdecksbuilder.client/Dockerfile'
#     buildContext: 'mtgcustomdecksbuilder.client/dist/mtgcustomdecksbuilder.client'
#     tags: 'mtg-client:staging'

- script: |
    npm run build mtgcustomdecksbuilder.client --configuration=production
  workingDirectory: 'mtgcustomdecksbuilder.client'
  displayName: 'Build Angular Client (Production)'

- task: CopyFiles@2
  displayName: 'Prepare Docker Context for Angular Client (Production)'
  inputs:
    SourceFolder: 'mtgcustomdecksbuilder.client'
    Contents: |
      Dockerfile
      dist/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)/docker-client-production'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/docker-client-production'
    artifactName: 'docker-client-production'
    publishLocation: 'Container'

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathToPublish: 'mtgcustomdecksbuilder.client/dist/mtgcustomdecksbuilder.client'
#     artifactName: 'client-production'
#     publishLocation: 'Container'
#   displayName: 'Publish Angular Client (Production)'

# - task: Docker@2
#   displayName: 'Build Angular Client Docker Image (Production)'
#   inputs:
#     command: 'build'
#     dockerfile: 'mtgcustomdecksbuilder.client/Dockerfile'
#     buildContext: 'mtgcustomdecksbuilder.client/dist/mtgcustomdecksbuilder.client'
#     tags: 'mtg-client:production'

- task: ExtractFiles@1
  displayName: 'Extract .NET Server Artifact (Staging)'
  inputs:
    archiveFilePatterns: '$(build.artifactStagingDirectory)/WebApp.Staging.zip'
    destinationFolder: '$(Build.ArtifactStagingDirectory)/docker-server-staging'
    cleanDestinationFolder: true

- task: CopyFiles@2
  displayName: 'Add Dockerfile to Server Context (Staging)'
  inputs:
    SourceFolder: 'mtgcustomdecksbuilder.server'
    Contents: Dockerfile
    TargetFolder: '$(Build.ArtifactStagingDirectory)/docker-server-staging'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/docker-server-staging'
    artifactName: 'docker-server-staging'
    publishLocation: 'Container'

# - task: CopyFiles@2
#   displayName: 'Prepare Docker Context for NET Server (Staging)'
#   inputs:
#     SourceFolder: 'mtgcustomdecksbuilder.server'
#     Contents: |
#       Dockerfile
#       dist/**
#     TargetFolder: '$(Build.ArtifactStagingDirectory)/docker-server-staging'

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathToPublish: '$(Build.ArtifactStagingDirectory)/docker-server-staging'
#     artifactName: 'docker-server-staging'
#     publishLocation: 'Container'

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathToPublish: '$(build.artifactStagingDirectory)/WebApp.Staging.zip'
#     artifactName: 'server-staging'
#     publishLocation: 'Container'
#   displayName: 'Publish .NET Server (Staging)'

# - task: ExtractFiles@1
#   inputs:
#     archiveFilePatterns: '$(build.artifactStagingDirectory)/WebApp.Staging.zip'
#     destinationFolder: '$(Build.ArtifactStagingDirectory)/server-staging'
#     cleanDestinationFolder: true

# - task: Docker@2
#   displayName: 'Build .NET Server Docker Image (Staging)'
#   inputs:
#     command: 'build'
#     dockerfile: 'MtgCustomDecksBuilder.Server/Dockerfile'
#     buildContext: '$(Build.ArtifactStagingDirectory)/server-staging'
#     tags: 'mtg-server:staging'

- task: ExtractFiles@1
  displayName: 'Extract .NET Server Artifact (Production)'
  inputs:
    archiveFilePatterns: '$(build.artifactStagingDirectory)/WebApp.Production.zip'
    destinationFolder: '$(Build.ArtifactStagingDirectory)/docker-server-production'
    cleanDestinationFolder: true

- task: CopyFiles@2
  displayName: 'Add Dockerfile to Server Context (Production)'
  inputs:
    SourceFolder: 'mtgcustomdecksbuilder.server'
    Contents: Dockerfile
    TargetFolder: '$(Build.ArtifactStagingDirectory)/docker-server-production'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/docker-server-production'
    artifactName: 'docker-server-production'
    publishLocation: 'Container'

# - task: CopyFiles@2
#   displayName: 'Prepare Docker Context for NET Server (Production)'
#   inputs:
#     SourceFolder: 'mtgcustomdecksbuilder.server'
#     Contents: |
#       Dockerfile
#       dist/**
#     TargetFolder: '$(Build.ArtifactStagingDirectory)/docker-server-production'

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathToPublish: '$(Build.ArtifactStagingDirectory)/docker-server-production'
#     artifactName: 'docker-server-production'
#     publishLocation: 'Container'

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathToPublish: '$(build.artifactStagingDirectory)/WebApp.Production.zip'
#     artifactName: 'server-production'
#     publishLocation: 'Container'
#   displayName: 'Publish NET Server (Production)'

# - task: ExtractFiles@1
#   inputs:
#     archiveFilePatterns: '$(build.artifactStagingDirectory)/WebApp.Production.zip'
#     destinationFolder: '$(Build.ArtifactStagingDirectory)/server-production'
#     cleanDestinationFolder: true

# - task: Docker@2
#   displayName: 'Build .NET Server Docker Image (Production)'
#   inputs:
#     command: 'build'
#     dockerfile: 'MtgCustomDecksBuilder.Server/Dockerfile'
#     buildContext: '$(Build.ArtifactStagingDirectory)/server-production'
#     tags: 'mtg-server:production'
