# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfigurationRelease: 'Release'
  buildConfigurationStaging: 'Stg'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: 'MtgCustomDecksBuilder.Server/MtgCustomDecksBuilder.Server.csproj'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.Staging.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfigurationStaging)'
  displayName: 'Build Staging Server'

- task: VSBuild@1
  inputs:
    solution: 'MtgCustomDecksBuilder.Server/MtgCustomDecksBuilder.Server.csproj'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.Production.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfigurationRelease)'
  displayName: 'Build Production Server'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  displayName: 'Install Angular Dependencies'
  inputs:
    workingDirectory: 'mtgcustomdecksbuilder.client'
    script: 'npm install'

- script: |
    cd src/client
    npm run build -- --configuration staging
  displayName: 'Build Angular Client (Staging)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'dist/mtgcustomdecksbuilder.client'
    artifactName: 'client-staging'
    publishLocation: 'Container'

- script: |
    cd src/client
    npm run build -- --configuration production
  displayName: 'Build Angular Client (Production)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'dist/mtgcustomdecksbuilder.client'
    artifactName: 'client-production'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/WebApp.Staging.zip'
    artifactName: 'server-staging'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/WebApp.Production.zip'
    artifactName: 'server-production'
    publishLocation: 'Container'